name: Bangun Anon-Mumble OFAID

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  android:
    name: Bangun APK Rilis
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Ambil kode & submodul
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Siapkan Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Siapkan Android SDK
        uses: android-actions/setup-android@v3

      - name: Izin jalankan Gradle
        run: chmod +x gradlew

      - name: Bangun Versi Rilis
        run: ./gradlew assembleRelease

      - name: Simpan APK hasil
        uses: actions/upload-artifact@v4
        with:
          name: AnonMumble-Rilis
          path: app/build/outputs/apk/release/*.apk
          retention-days: 30
